global:
  blueGreen:
    image: argoproj/rollouts-demo:blue

replicaCount: 2
revisionHistoryLimit: 2

rollout:
  name: rollout-bluegreen
  namespace: blue-green
  activeService: rollout-bluegreen-active
  previewService: rollout-bluegreen-preview
  
  blue:
    serviceName: rollout-bluegreen-active
  green:

image:
  pullPolicy: Always

containers:
  name: rollouts-demo
  ports:
    containerPort: 8080

strategy:
  blueGreen:
    autoPromotionEnabled: false

service:
  protocol: TCP
  port: 80
  targetPort: 8080

route:
- name: rollout-bluegreen-active
  kind: Service
  weight: 100
  port:
    targetPort: 8080
- name: rollout-bluegreen-preview
  kind: Service
  weight: 100
  port:
    targetPort: 8080