apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: engine
  namespace: {{ .Values.operator.name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  availabilityConfig: High
  overrides:
    components:
{{- range .Values.mce.overrides.components }}
    - enabled: {{ .enabled }}
      name: {{ .name }} 
{{- end }}
  targetNamespace: {{ .Values.operator.name }}
