apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: multicluster-engine
  namespace: {{ .Release.namespace }}
spec:
  targetNamespaces:
  - multicluster-engine
  upgradeStrategy: Default
